export const SET_LOGGED_USER_INFO = 'SET_LOGGED_USER_INFO';
export const SET_CONTACT_USER = 'SET_CONTACT_USER';
export const SET_CURRENT_VIEW_USER = 'SET_CURRENT_VIEW_USER';
export const SET_USER_MESSAGE = 'SET_USER_MESSAGE';
export const SET_RESET_STORE = 'SET_RESET_STORE';
